const Joi = require('joi');

const IndustrialVesselInspectionCreate = Joi.object().keys({
    create_by: Joi.string().required(),
    type_fishshop: Joi.string().required(),
    landing_site: Joi.string().required(),
    arrival_date: Joi.number().required(),
    sailing_date: Joi.number().required(),
    boat_name: Joi.string().required(),
    captain_name: Joi.string().required(),
    permit_holder: Joi.string().required(),
    patent_number: Joi.string().required(),
    expiration_date: Joi.number().required(),
    field_recorder: Joi.string().required(),
    number_fishermen_resident: Joi.string().required(),
    number_fishermen_foreign: Joi.string().required(),
    number_fishermen_continental: Joi.string().required(),
    number_crew_resident: Joi.string().required(),
    number_crew_foreign: Joi.string().required(),
    number_crew_continental: Joi.string().required(),
    fishing_areas: Joi.array().required(),
    diving_number_pangas_perday: Joi.string().required(),
    diving_number_divers_perpanga: Joi.string().required(),
    diving_effort_diver_perday: Joi.string().required(),
    lobster_pots_number_lines_perdays: Joi.string().required(),
    lobster_pots_number_lingadas_perlines: Joi.string().required(),
    lobster_pots_number_nasa_perlingada: Joi.string().required(),
    lobster_pots_effort: Joi.string().required(),
    fish_pots_type: Joi.string().required(),
    fish_pots_number_pots_perday: Joi.string().required(),
    fish_pots_effort_pots_perday: Joi.string().required(),
    long_line: Joi.string().required(),
    longLine: Joi.array().required(),
    reel: Joi.array().required(),
    transshipment_control: Joi.array().required(),
    transshipment_product_control: Joi.array().required(),
    control_total_bags_landed: Joi.string().required(),
    control_total_sealed_bags: Joi.string().required(),
    number_seals: Joi.array().required(),
    observations: Joi.string().required(),
    signatureRegister: Joi.string().required(),
    signatureCaptainOrRepresentative: Joi.string().required(),
    issue_date: Joi.number().required()
});

const IndustrialVesselInspectionUpdate = Joi.object().keys({
    _id: Joi.string().required(),
    create_by: Joi.string().required(),
    type_fishshop: Joi.string().required(),
    landing_site: Joi.string().required(),
    arrival_date: Joi.number().required(),
    sailing_date: Joi.number().required(),
    boat_name: Joi.string().required(),
    captain_name: Joi.string().required(),
    permit_holder: Joi.string().required(),
    patent_number: Joi.string().required(),
    expiration_date: Joi.number().required(),
    field_recorder: Joi.string().required(),
    number_fishermen_resident: Joi.string().required(),
    number_fishermen_foreign: Joi.string().required(),
    number_fishermen_continental: Joi.string().required(),
    number_crew_resident: Joi.string().required(),
    number_crew_foreign: Joi.string().required(),
    number_crew_continental: Joi.string().required(),
    fishing_areas: Joi.array().required(),
    diving_number_pangas_perday: Joi.string().required(),
    diving_number_divers_perpanga: Joi.string().required(),
    diving_effort_diver_perday: Joi.string().required(),
    lobster_pots_number_lines_perdays: Joi.string().required(),
    lobster_pots_number_lingadas_perlines: Joi.string().required(),
    lobster_pots_number_nasa_perlingada: Joi.string().required(),
    lobster_pots_effort: Joi.string().required(),
    fish_pots_type: Joi.string().required(),
    fish_pots_number_pots_perday: Joi.string().required(),
    fish_pots_effort_pots_perday: Joi.string().required(),
    long_line: Joi.string().required(),
    longLine: Joi.array().required(),
    reel: Joi.array().required(),
    transshipment_control: Joi.array().required(),
    transshipment_product_control: Joi.array().required(),
    control_total_bags_landed: Joi.string().required(),
    control_total_sealed_bags: Joi.string().required(),
    number_seals: Joi.array().required(),
    observations: Joi.string().required(),
    signatureRegister: Joi.string().required(),
    signatureCaptainOrRepresentative: Joi.string().required(),
    issue_date: Joi.number().required()
});

module.exports = {
    IndustrialVesselInspectionCreate,
    IndustrialVesselInspectionUpdate
}
